#!/bin/sh
# wrapper around runit 'sv status' command
# (cloux@rote.ch)

# need to be root
if [ $(id -u) -ne 0 ]; then printf '%s: Need to be root!\n' "$0"; exit 1; fi

cd /etc/service/ || exit 1
if [ $# -eq 0 ]; then
	sv status *
else
	sv status $@
fi
